# Generated by Django 5.2 on 2025-10-31 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentorder',
            name='provider',
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='order_reference',
            field=models.CharField(blank=True, help_text='Order reference identifier', max_length=100),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='payment_provider',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('paytm', 'Paytm'), ('phonepe', 'PhonePe'), ('gpay', 'Google Pay'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer')], default='razorpay', help_text='Payment provider name', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='order_id',
            field=models.CharField(blank=True, help_text='Unique order identifier', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('paid', 'Paid'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('unpaid', 'Unpaid')], default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('paid', 'Paid'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('unpaid', 'Unpaid')], default='pending', max_length=20),
        ),
    ]
