# Generated by Django 5.2.1 on 2025-12-26 19:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_add_financial_snapshot_and_retry_tracking'),
        ('payments', '0002_alter_paymentorder_user'),
        ('users', '0003_userprofile_waitlist_promote_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='base_price_per_seat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base ticket price per seat at payment time (immutable snapshot)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='host_earning_per_seat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Host earning per seat at payment time (immutable snapshot, equals base_price_per_seat)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='is_final',
            field=models.BooleanField(default=False, help_text='True if this is the final successful payment (not a retry attempt)'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='parent_order',
            field=models.ForeignKey(blank=True, help_text='Parent order if this is a retry attempt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retry_attempts', to='payments.paymentorder'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='platform_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total platform fee amount at payment time (immutable snapshot)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='platform_fee_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Platform fee percentage at payment time (immutable snapshot, e.g., 10.00 for 10%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='seats_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of seats/tickets this payment covers'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Total amount paid (includes base price + platform fee)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='event',
            field=models.ForeignKey(help_text='Event for which payment is being made', on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to='events.event'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='payment_provider',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('paytm', 'Paytm'), ('phonepe', 'PhonePe'), ('gpay', 'Google Pay'), ('payu', 'PayU'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer')], default='razorpay', help_text='Payment provider name', max_length=50),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['is_final'], name='payments_pa_is_fina_3ee245_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['parent_order'], name='payments_pa_parent__070895_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['event', 'user', 'is_final'], name='payments_pa_event_i_05bf95_idx'),
        ),
    ]
