# Generated by Django 5.2.1 on 2025-12-26 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_add_financial_snapshot_and_retry_tracking'),
    ]

    operations = [
    ]
