# Generated by Django 5.2 on 2025-11-10 21:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(help_text='Name of the event interest', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly slug', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the event interest')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this interest is active')),
            ],
            options={
                'verbose_name': 'Event Interest',
                'verbose_name_plural': 'Event Interests',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HostLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First name of the potential host', max_length=100)),
                ('last_name', models.CharField(help_text='Last name of the potential host', max_length=100)),
                ('phone_number', models.CharField(help_text='Phone number of the potential host', max_length=20, unique=True)),
                ('message', models.TextField(blank=True, help_text='Optional message from the potential host')),
                ('is_contacted', models.BooleanField(default=False, help_text='Whether the lead has been contacted')),
                ('is_converted', models.BooleanField(default=False, help_text='Whether the lead became a host')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the lead')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Host Lead',
                'verbose_name_plural': 'Host Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HostLeadWhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Short identifier for the marketing message (e.g., 'Intro Message').", max_length=120, unique=True)),
                ('message', models.TextField(help_text='Pre-approved copy inserted into template variable {{2}}.')),
            ],
            options={
                'verbose_name': 'Host Lead WhatsApp Template',
                'verbose_name_plural': 'Host Lead WhatsApp Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('otp_code', models.CharField(max_length=6)),
                ('otp_type', models.CharField(choices=[('signup', 'Signup'), ('login', 'Login'), ('password_reset', 'Password Reset'), ('phone_verification', 'Phone Verification'), ('transaction', 'Transaction')], default='signup', help_text='Type of OTP (signup, login, etc.)', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('expired', 'Expired'), ('failed', 'Failed')], default='pending', help_text='OTP verification status', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Phone OTP',
                'verbose_name_plural': 'Phone OTPs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HostLeadWhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('content_sid', models.CharField(help_text='Twilio Content Template SID used for this send', max_length=80)),
                ('variables', models.JSONField(default=dict, help_text="Content variables sent to Twilio (e.g., {'1': 'Name', '2': 'Message'})")),
                ('body_variable', models.TextField(help_text='Final text value used for variable {{2}}')),
                ('status', models.CharField(choices=[('queued', 'Queued / Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('undelivered', 'Undelivered'), ('failed', 'Failed'), ('test-mode', 'Test Mode')], default='queued', help_text='Latest known delivery status', max_length=20)),
                ('twilio_sid', models.CharField(blank=True, help_text='Twilio message SID for tracking', max_length=64)),
                ('error_code', models.CharField(blank=True, help_text='Twilio error code (if any)', max_length=50)),
                ('error_message', models.TextField(blank=True, help_text='Human-readable error message (if any)')),
                ('lead', models.ForeignKey(help_text='Host lead recipient', on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='users.hostlead')),
                ('sent_by', models.ForeignKey(blank=True, help_text='Admin user who triggered the message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostlead_whatsapp_messages', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, help_text='Template used (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='users.hostleadwhatsapptemplate')),
            ],
            options={
                'verbose_name': 'Host Lead WhatsApp Message',
                'verbose_name_plural': 'Host Lead WhatsApp Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public UUID', unique=True)),
                ('name', models.CharField(blank=True, help_text='Full name of the user', max_length=100)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=15)),
                ('bio', models.TextField(blank=True, help_text='User biography', max_length=500)),
                ('location', models.CharField(blank=True, help_text='User location', max_length=100)),
                ('birth_date', models.DateField(blank=True, help_text='Date of birth', null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], help_text='User gender', max_length=20)),
                ('profile_pictures', models.JSONField(blank=True, default=list, help_text='List of profile picture URLs (1-6 pictures required)')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the user profile is verified')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the user profile is active')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata')),
                ('event_interests', models.ManyToManyField(blank=True, help_text="User's event interests (1-5 selections required)", to='users.eventinterest')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
