# Generated by Django 5.2.1 on 2025-11-24 20:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public UUID', unique=True)),
                ('bank_name', models.CharField(help_text="Name of the bank (e.g., 'State Bank of India', 'HDFC Bank')", max_length=100)),
                ('account_number', models.CharField(help_text='Bank account number', max_length=30)),
                ('ifsc_code', models.CharField(help_text='IFSC (Indian Financial System Code) - 11 characters', max_length=11)),
                ('account_holder_name', models.CharField(help_text='Name of the account holder as registered with the bank', max_length=100)),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary bank account for payouts')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether this bank account has been verified')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this bank account is active and can receive payouts')),
                ('host', models.ForeignKey(help_text='Host user who owns this bank account', on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HostPayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public UUID', unique=True)),
                ('host_name', models.CharField(help_text='Host name at the time of request', max_length=200)),
                ('event_name', models.CharField(help_text='Event name at the time of request', max_length=255)),
                ('event_date', models.DateTimeField(help_text='Event date (start_time) at the time of request')),
                ('event_location', models.CharField(help_text='Event location (venue name or venue_text) at the time of request', max_length=255)),
                ('total_capacity', models.PositiveIntegerField(help_text='Total event capacity at the time of request')),
                ('base_ticket_fare', models.DecimalField(decimal_places=2, help_text='Base ticket price per attendee', max_digits=10)),
                ('final_ticket_fare', models.DecimalField(decimal_places=2, help_text='Final ticket price including 10% platform fee', max_digits=10)),
                ('total_tickets_sold', models.PositiveIntegerField(help_text='Total number of tickets sold at the time of request')),
                ('attendees_details', models.JSONField(default=list, help_text='List of attendees with name and contact at the time of request')),
                ('platform_fee_amount', models.DecimalField(decimal_places=2, help_text='Total platform fee (10% of base ticket fare × tickets sold)', max_digits=10)),
                ('final_earning', models.DecimalField(decimal_places=2, help_text='Host earnings: Base ticket fare × tickets sold (platform fee is added on top, not deducted)', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the payout request', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, help_text='Timestamp when payout was processed', null=True)),
                ('transaction_reference', models.CharField(blank=True, help_text='Bank transaction reference number', max_length=100)),
                ('rejection_reason', models.TextField(blank=True, help_text="Reason for rejection if status is 'rejected'")),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this payout request')),
                ('bank_account', models.ForeignKey(help_text='Bank account to receive the payout', on_delete=django.db.models.deletion.PROTECT, related_name='payout_requests', to='users.bankaccount')),
                ('event', models.ForeignKey(help_text='Event for which payout is requested', on_delete=django.db.models.deletion.PROTECT, related_name='payout_requests', to='events.event')),
            ],
            options={
                'verbose_name': 'Host Payout Request',
                'verbose_name_plural': 'Host Payout Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['host'], name='users_banka_host_id_9aceb3_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['is_primary'], name='users_banka_is_prim_d3fa5b_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['is_active'], name='users_banka_is_acti_9bd641_idx'),
        ),
        migrations.AddIndex(
            model_name='hostpayoutrequest',
            index=models.Index(fields=['event'], name='users_hostp_event_i_1e527a_idx'),
        ),
        migrations.AddIndex(
            model_name='hostpayoutrequest',
            index=models.Index(fields=['bank_account'], name='users_hostp_bank_ac_dd977c_idx'),
        ),
        migrations.AddIndex(
            model_name='hostpayoutrequest',
            index=models.Index(fields=['status'], name='users_hostp_status_3c9003_idx'),
        ),
        migrations.AddIndex(
            model_name='hostpayoutrequest',
            index=models.Index(fields=['event_date'], name='users_hostp_event_d_d5f839_idx'),
        ),
    ]
