# Generated by Django 5.2.1 on 2025-12-22 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_bank_account_and_payout_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='waitlist_promote_at',
            field=models.DateTimeField(blank=True, help_text='Scheduled promotion time from waitlist to active state', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='waitlist_started_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the user was first placed on the waitlist', null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='host',
            field=models.ForeignKey(help_text='Host user profile who owns this bank account', on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='users.userprofile'),
        ),
    ]
