# Generated by Django 5.2.1 on 2025-12-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_waitlist_promote_at_and_more'),
        ('payments', '0003_add_financial_snapshot_and_retry_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostpayoutrequest',
            name='payment_orders',
            field=models.ManyToManyField(blank=True, help_text='Payment orders that funded this payout (for reconciliation)', related_name='payout_requests', to='payments.paymentorder'),
        ),
    ]
