# Generated by Django 5.2 on 2025-10-06 11:49

from django.db import migrations


def clear_existing_otps(apps, schema_editor):
    """Clear existing OTP records to avoid data truncation issues"""
    PhoneOTP = apps.get_model('users', 'PhoneOTP')
    PhoneOTP.objects.all().delete()


def reverse_clear_otps(apps, schema_editor):
    """No reverse operation needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_phoneotp'),
    ]

    operations = [
        migrations.RunPython(clear_existing_otps, reverse_clear_otps),
    ]