# Generated by Django 5.2.1 on 2025-12-27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_financial_snapshot_and_retry_tracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventinterest',
            name='description',
        ),
    ]

