# Generated by Django 5.2 on 2025-10-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20251006_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the event interest', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the event interest')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this interest is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event Interest',
                'verbose_name_plural': 'Event Interests',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='User gender', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_pictures',
            field=models.JSONField(blank=True, default=list, help_text='List of profile picture URLs (1-6 pictures required)'),
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='otp_code',
            field=models.CharField(max_length=4),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='event_interests',
            field=models.ManyToManyField(blank=True, help_text="User's event interests (1-5 selections required)", to='users.eventinterest'),
        ),
    ]
