# Generated by Django 5.2 on 2025-10-06 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_eventinterest_userprofile_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
