# Generated by Django 5.2.1 on 2026-01-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_eventinterest_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='otp_type',
            field=models.CharField(choices=[('signup', 'Signup'), ('login', 'Login'), ('password_reset', 'Password Reset'), ('phone_verification', 'Phone Verification'), ('transaction', 'Transaction')], default='signup', help_text='Type of OTP for normal users (signup, login, password_reset, phone_verification, transaction)', max_length=20),
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='phone_number',
            field=models.CharField(help_text='Phone number used by normal users (customers) for authentication. Links to USER_PROFILE.phone_number.', max_length=15, unique=True),
        ),
    ]
