# Generated by Django 5.2 on 2025-10-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_userprofile_avatar_remove_userprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First name of the potential host', max_length=100)),
                ('last_name', models.CharField(help_text='Last name of the potential host', max_length=100)),
                ('email', models.EmailField(help_text='Email address of the potential host', max_length=254, unique=True)),
                ('is_contacted', models.BooleanField(default=False, help_text='Whether the lead has been contacted')),
                ('is_converted', models.BooleanField(default=False, help_text='Whether the lead became a host')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the lead')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Host Lead',
                'verbose_name_plural': 'Host Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
