# Generated by Django 5.2 on 2025-10-30 19:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_phoneotp_otp_type_phoneotp_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinterest',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly slug', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public UUID', unique=True),
        ),
    ]
