# Generated by Django 5.2 on 2025-10-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_hostlead_email_to_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostlead',
            name='message',
            field=models.TextField(blank=True, help_text='Optional message from the potential host'),
        ),
    ]
