# Generated by Django 5.2 on 2025-11-03 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_hostlead_message'),
        ('users', '0011_add_unique_slug'),
    ]

    operations = [
    ]
