# Generated by Django 5.2 on 2025-11-10 21:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public UUID', unique=True)),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinValueValidator(3)])),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly slug', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, validators=[django.core.validators.MinValueValidator(10)])),
                ('venue_text', models.CharField(blank=True, help_text='Custom venue if not in VENUE table', max_length=255)),
                ('start_time', models.DateTimeField(help_text='Event start date and time')),
                ('end_time', models.DateTimeField(help_text='Event end date and time')),
                ('max_capacity', models.PositiveIntegerField(default=0, help_text='Maximum attendees')),
                ('is_paid', models.BooleanField(default=False, help_text='Whether event requires payment')),
                ('ticket_price', models.DecimalField(decimal_places=2, default=0, help_text='Ticket price', max_digits=10)),
                ('allow_plus_one', models.BooleanField(default=True, help_text='Allow bringing a guest')),
                ('gst_number', models.CharField(blank=True, help_text='Host GST number', max_length=50)),
                ('allowed_genders', models.CharField(choices=[('all', 'All'), ('male', 'Male Only'), ('female', 'Female Only'), ('non_binary', 'Non-binary')], default='all', help_text='Gender restrictions', max_length=20)),
                ('cover_images', models.JSONField(blank=True, default=list, help_text='Array of 1-3 cover image URLs')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('postponed', 'Postponed')], default='draft', help_text='Event status', max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('going_count', models.PositiveIntegerField(default=0, help_text='Number of confirmed attendees')),
                ('requests_count', models.PositiveIntegerField(default=0, help_text='Number of pending requests')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('invite_type', models.CharField(choices=[('direct', 'Direct'), ('share_link', 'Share Link')], default='direct', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='events.event')),
                ('host', models.ForeignKey(blank=True, help_text='Event host (optional, can be derived from event.host)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_event_invites', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_invites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('host_message', models.TextField(blank=True, help_text="Host's response message")),
                ('seats_requested', models.PositiveIntegerField(default=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='events.event')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ticket_type', models.CharField(choices=[('standard', 'Standard'), ('vip', 'VIP'), ('early_bird', 'Early Bird'), ('premium', 'Premium'), ('general', 'General'), ('group', 'Group'), ('couple', 'Couple'), ('family', 'Family'), ('student', 'Student'), ('senior_citizen', 'Senior Citizen'), ('disabled', 'Disabled'), ('other', 'Other')], default='general', max_length=20)),
                ('seats', models.PositiveIntegerField(default=1)),
                ('is_paid', models.BooleanField(default=False)),
                ('price_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('going', 'Going'), ('not_going', 'Not Going'), ('maybe', 'Maybe'), ('checked_in', 'Checked In'), ('cancelled', 'Cancelled')], default='going', max_length=20)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to=settings.AUTH_USER_MODEL)),
                ('invite', models.ForeignKey(blank=True, help_text='Originating invitation if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendees', to='events.eventinvite')),
                ('request', models.ForeignKey(blank=True, help_text='Originating request if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendees', to='events.eventrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public UUID', unique=True)),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('venue_type', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('virtual', 'Virtual'), ('hybrid', 'Hybrid')], default='indoor', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=0, help_text='Informational capacity hint only—actual capacity controlled by Event.max_capacity')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra info, accessibility, capacity hints')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['city'], name='events_venu_city_614bce_idx'), models.Index(fields=['venue_type'], name='events_venu_venue_t_8565ea_idx'), models.Index(fields=['is_active'], name='events_venu_is_acti_822dec_idx')],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.venue'),
        ),
        migrations.CreateModel(
            name='CapacityReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('reservation_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('seats_reserved', models.PositiveIntegerField(default=1)),
                ('consumed', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_reservations', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_reservations', to='events.event')),
            ],
            options={
                'indexes': [models.Index(fields=['expires_at'], name='events_capa_expires_a7d6ed_idx'), models.Index(fields=['consumed'], name='events_capa_consume_0ab419_idx'), models.Index(fields=['event', 'user'], name='events_capa_event_i_67cff5_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('image_url', models.TextField(help_text='Image URL')),
                ('position', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_images', to='events.event')),
            ],
            options={
                'ordering': ['position'],
                'indexes': [models.Index(fields=['event', 'position'], name='events_even_event_i_beb1fe_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventInterestMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_maps', to='events.event')),
                ('event_interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_maps', to='users.eventinterest')),
            ],
            options={
                'indexes': [models.Index(fields=['event', 'event_interest'], name='events_even_event_i_b52497_idx')],
                'unique_together': {('event', 'event_interest')},
            },
        ),
        migrations.AddIndex(
            model_name='eventinvite',
            index=models.Index(fields=['status'], name='events_even_status_aac396_idx'),
        ),
        migrations.AddIndex(
            model_name='eventinvite',
            index=models.Index(fields=['event', 'invited_user'], name='events_even_event_i_627799_idx'),
        ),
        migrations.AddIndex(
            model_name='eventinvite',
            index=models.Index(fields=['expires_at'], name='events_even_expires_f869ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventinvite',
            unique_together={('event', 'invited_user')},
        ),
        migrations.AddIndex(
            model_name='eventrequest',
            index=models.Index(fields=['status'], name='events_even_status_72eada_idx'),
        ),
        migrations.AddIndex(
            model_name='eventrequest',
            index=models.Index(fields=['event', 'requester'], name='events_even_event_i_f96765_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventrequest',
            unique_together={('event', 'requester')},
        ),
        migrations.AddIndex(
            model_name='eventattendee',
            index=models.Index(fields=['status'], name='events_even_status_cbaf98_idx'),
        ),
        migrations.AddIndex(
            model_name='eventattendee',
            index=models.Index(fields=['event', 'user'], name='events_even_event_i_21ef35_idx'),
        ),
        migrations.AddIndex(
            model_name='eventattendee',
            index=models.Index(fields=['request'], name='events_even_request_f45f87_idx'),
        ),
        migrations.AddIndex(
            model_name='eventattendee',
            index=models.Index(fields=['invite'], name='events_even_invite__7a559a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventattendee',
            unique_together={('event', 'user')},
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_time'], name='events_even_start_t_c2d277_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status'], name='events_even_status_5709b6_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_public'], name='events_even_is_publ_e2e10e_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_active'], name='events_even_is_acti_82811f_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['host'], name='events_even_host_id_59d663_idx'),
        ),
    ]
