# Generated by Django 5.2.1 on 2025-12-22 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('users', '0003_userprofile_waitlist_promote_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacityreservation',
            name='user',
            field=models.ForeignKey(help_text='User profile reserving capacity', on_delete=django.db.models.deletion.CASCADE, related_name='capacity_reservations', to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='event',
            name='host',
            field=models.ForeignKey(help_text='Host user profile who owns this event', on_delete=django.db.models.deletion.CASCADE, related_name='hosted_events', to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='eventattendee',
            name='user',
            field=models.ForeignKey(help_text='Attending user profile', on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='eventinvite',
            name='host',
            field=models.ForeignKey(blank=True, help_text='Host user profile (optional, can be derived from event.host)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_event_invites', to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='eventinvite',
            name='invited_user',
            field=models.ForeignKey(help_text='Invited user profile', on_delete=django.db.models.deletion.CASCADE, related_name='event_invites', to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='eventrequest',
            name='requester',
            field=models.ForeignKey(help_text='User profile requesting to join event', on_delete=django.db.models.deletion.CASCADE, related_name='event_requests', to='users.userprofile'),
        ),
    ]
