# Generated by Django 5.2.1 on 2025-12-26 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_capacityreservation_user_alter_event_host_and_more'),
        ('payments', '0003_add_financial_snapshot_and_retry_tracking'),
        ('users', '0003_userprofile_waitlist_promote_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventattendee',
            name='payment_order',
            field=models.ForeignKey(blank=True, help_text='Payment order that fulfilled this attendee (for paid events)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_attendees', to='payments.paymentorder'),
        ),
        migrations.AddIndex(
            model_name='eventattendee',
            index=models.Index(fields=['payment_order'], name='events_even_payment_04f393_idx'),
        ),
    ]
