# Generated by Django 5.2.1 on 2026-01-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_add_financial_snapshot_and_retry_tracking'),
        ('users', '0006_alter_phoneotp_otp_type_alter_phoneotp_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='canonical_id',
            field=models.CharField(blank=True, db_index=True, help_text='Immutable Base62 identifier for canonical URLs (generated at creation)', max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='event',
            name='canonical_url',
            field=models.TextField(blank=True, db_index=True, help_text='Full canonical URL path: /{country_code}/{city_slug}/events/{slug}--{canonical_id}', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='event',
            name='slug_version',
            field=models.PositiveIntegerField(default=1, help_text='Increments on every slug change for cache busting'),
        ),
        migrations.AddField(
            model_name='venue',
            name='city_slug',
            field=models.CharField(blank=True, help_text='URL-safe city name slug for canonical URLs (auto-generated from city)', max_length=100),
        ),
        migrations.AddField(
            model_name='venue',
            name='country_code',
            field=models.CharField(default='in', help_text="ISO 3166-1 alpha-2 country code (e.g., 'in', 'us') for GEO SEO", max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.CharField(blank=True, help_text='SEO-friendly slug (max 70 chars, can change, not unique)', max_length=70),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['canonical_id'], name='events_even_canonic_d7a75d_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['canonical_url'], name='events_even_canonic_0913b3_idx'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['country_code', 'city_slug'], name='events_venu_country_c0cf68_idx'),
        ),
    ]
