# Generated by Django 5.2 on 2025-10-31 09:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_add_unique_slug'),
        ('users', '0011_add_unique_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='metadata',
        ),
        migrations.AddField(
            model_name='event',
            name='allow_plus_one',
            field=models.BooleanField(default=True, help_text='Allow bringing a guest'),
        ),
        migrations.AddField(
            model_name='event',
            name='allowed_genders',
            field=models.CharField(choices=[('all', 'All'), ('male', 'Male Only'), ('female', 'Female Only'), ('non_binary', 'Non-binary')], default='all', help_text='Gender restrictions', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='gst_number',
            field=models.CharField(blank=True, help_text='Host GST number', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Whether event requires payment'),
        ),
        migrations.AddField(
            model_name='event',
            name='requests_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of pending requests'),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ticket price', max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_text',
            field=models.CharField(blank=True, help_text='Custom venue if not in VENUE table', max_length=255),
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='price_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendees', to='events.eventrequest'),
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='ticket_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('vip', 'VIP'), ('early_bird', 'Early Bird'), ('premium', 'Premium'), ('general', 'General'), ('group', 'Group'), ('couple', 'Couple'), ('family', 'Family'), ('student', 'Student'), ('senior_citizen', 'Senior Citizen'), ('disabled', 'Disabled'), ('other', 'Other')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='eventinvite',
            name='host',
            field=models.ForeignKey(blank=True, help_text='Event host (optional, can be derived from event.host)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_event_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventinvite',
            name='invite_type',
            field=models.CharField(choices=[('direct', 'Direct'), ('share_link', 'Share Link')], default='direct', max_length=20),
        ),
        migrations.AddField(
            model_name='eventinvite',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='host_message',
            field=models.TextField(blank=True, help_text="Host's response message"),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Extra info, accessibility, capacity hints'),
        ),
        migrations.AddField(
            model_name='venue',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public UUID', unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='cover_images',
            field=models.JSONField(blank=True, default=list, help_text='Array of 1-3 cover image URLs'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(help_text='Event end date and time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='going_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of confirmed attendees'),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_capacity',
            field=models.PositiveIntegerField(default=0, help_text='Maximum attendees'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(help_text='Event start date and time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('postponed', 'Postponed')], default='draft', help_text='Event status', max_length=20),
        ),
        migrations.CreateModel(
            name='CapacityReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('reservation_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('seats_reserved', models.PositiveIntegerField(default=1)),
                ('consumed', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_reservations', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['expires_at'], name='events_capa_expires_a7d6ed_idx'), models.Index(fields=['consumed'], name='events_capa_consume_0ab419_idx'), models.Index(fields=['event', 'user'], name='events_capa_event_i_67cff5_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('image_url', models.TextField(help_text='Image URL')),
                ('position', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_images', to='events.event')),
            ],
            options={
                'ordering': ['position'],
                'indexes': [models.Index(fields=['event', 'position'], name='events_even_event_i_beb1fe_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventInterestMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_maps', to='events.event')),
                ('event_interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_maps', to='users.eventinterest')),
            ],
            options={
                'indexes': [models.Index(fields=['event', 'event_interest'], name='events_even_event_i_b52497_idx')],
                'unique_together': {('event', 'event_interest')},
            },
        ),
    ]
