# Generated by Django 5.2 on 2025-11-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_uuid_alter_venue_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventattendee',
            name='ticket_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('vip', 'VIP'), ('early_bird', 'Early Bird'), ('premium', 'Premium'), ('general', 'General'), ('group', 'Group'), ('couple', 'Couple'), ('family', 'Family'), ('student', 'Student'), ('senior_citizen', 'Senior Citizen'), ('disabled', 'Disabled'), ('other', 'Other')], default='general', max_length=20),
        ),
    ]
