# Generated by Django 5.2 on 2025-11-04 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_eventattendee_ticket_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventattendee',
            name='invite',
            field=models.ForeignKey(blank=True, help_text='Originating invitation if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendees', to='events.eventinvite'),
        ),
        migrations.AlterField(
            model_name='eventattendee',
            name='request',
            field=models.ForeignKey(blank=True, help_text='Originating request if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendees', to='events.eventrequest'),
        ),
        migrations.AddIndex(
            model_name='eventattendee',
            index=models.Index(fields=['request'], name='events_even_request_f45f87_idx'),
        ),
        migrations.AddIndex(
            model_name='eventattendee',
            index=models.Index(fields=['invite'], name='events_even_invite__7a559a_idx'),
        ),
    ]
