# Generated by Django 5.2.1 on 2025-12-22 18:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformFeeConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.IntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('fee_percentage', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Platform fee percentage (0.00 to 100.00). Example: 10.00 = 10%', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this platform fee configuration is currently active')),
                ('description', models.TextField(blank=True, help_text='Optional description or notes about this fee configuration', max_length=500)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this configuration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_fee_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Fee Configuration',
                'verbose_name_plural': 'Platform Fee Configuration',
                'db_table': 'core_platform_fee_config',
            },
        ),
    ]
