# Generated by Django 5.2 on 2025-10-25 02:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', models.CharField(choices=[('going', 'Going'), ('not_going', 'Not Going'), ('maybe', 'Maybe'), ('checked_in', 'Checked In'), ('cancelled', 'Cancelled')], default='going', max_length=20)),
                ('payment_status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='unpaid', max_length=20)),
                ('ticket_secret', models.CharField(blank=True, max_length=64, unique=True)),
                ('seats', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('otp_code', models.CharField(max_length=4)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('attendance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_otps', to='attendances.attendancerecord')),
            ],
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['status'], name='attendances_status_571f50_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['payment_status'], name='attendances_payment_1f1e82_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['event', 'user'], name='attendances_event_i_4dfcbf_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['checked_in_at'], name='attendances_checked_757999_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('event', 'user')},
        ),
        migrations.AddIndex(
            model_name='attendanceotp',
            index=models.Index(fields=['otp_code'], name='attendances_otp_cod_bfcb74_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceotp',
            index=models.Index(fields=['is_used'], name='attendances_is_used_005fc1_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceotp',
            index=models.Index(fields=['expires_at'], name='attendances_expires_5fc8f5_idx'),
        ),
    ]
