# Generated by Django 5.2.1 on 2025-12-22 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0001_initial'),
        ('users', '0003_userprofile_waitlist_promote_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='user',
            field=models.ForeignKey(help_text='User profile attending the event', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='users.userprofile'),
        ),
    ]
