# Generated by Django 5.2 on 2025-10-31 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='payment_status',
            field=models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('paid', 'Paid'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('unpaid', 'Unpaid')], default='unpaid', max_length=20),
        ),
        migrations.CreateModel(
            name='TicketSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('secret_hash', models.TextField(help_text='Hashed ticket secret')),
                ('secret_salt', models.TextField(help_text='Salt for hashing')),
                ('is_redeemed', models.BooleanField(default=False, help_text='Whether ticket has been redeemed')),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('attendance_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_secret_obj', to='attendances.attendancerecord')),
            ],
            options={
                'indexes': [models.Index(fields=['is_redeemed'], name='attendances_is_rede_f499e9_idx')],
            },
        ),
    ]
