# Generated by Django 5.2.1 on 2025-12-26 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0002_fix_orphaned_and_alter_user_fk'),
        ('events', '0003_add_financial_snapshot_and_retry_tracking'),
        ('payments', '0003_add_financial_snapshot_and_retry_tracking'),
        ('users', '0004_add_financial_snapshot_and_retry_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='payment_order',
            field=models.ForeignKey(blank=True, help_text='Payment order that fulfilled this attendance (for paid events)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='payments.paymentorder'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['payment_order'], name='attendances_payment_08e3dd_idx'),
        ),
    ]
