# Generated by Django 5.2 on 2025-11-04 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0002_alter_attendancerecord_payment_status_ticketsecret'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendanceOTP',
        ),
    ]
