# Generated by Django 5.2 on 2025-11-10 21:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public UUID', unique=True)),
                ('type', models.CharField(choices=[('event_request', 'Event Request'), ('event_invite', 'Event Invite'), ('event_update', 'Event Update'), ('event_cancelled', 'Event Cancelled'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('reminder', 'Reminder'), ('system', 'System'), ('promotional', 'Promotional')], help_text='Type of notification', max_length=50)),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message')),
                ('reference_type', models.CharField(blank=True, help_text='Related model type (e.g., Event, Payment)', max_length=100)),
                ('reference_id', models.PositiveIntegerField(blank=True, help_text='Related object ID', null=True)),
                ('is_read', models.BooleanField(default=False, help_text='Whether notification has been read')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional notification data')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient'], name='notificatio_recipie_be3f1a_idx'), models.Index(fields=['sender'], name='notificatio_sender__b931be_idx'), models.Index(fields=['type'], name='notificatio_type_ea918f_idx'), models.Index(fields=['is_read'], name='notificatio_is_read_9edb86_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['reference_type', 'reference_id'], name='notificatio_referen_7d105c_idx')],
            },
        ),
    ]
