# Generated by Django 5.2.1 on 2025-12-22 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('users', '0003_userprofile_waitlist_promote_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(help_text='User profile receiving the notification', on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, help_text='User profile sending the notification (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to='users.userprofile'),
        ),
    ]
