# Generated by Django 5.2.1 on 2026-01-09 18:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_recipient_and_more'),
        ('users', '0006_alter_phoneotp_otp_type_alter_phoneotp_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('event_request', 'Event Request'), ('event_invite', 'Event Invite'), ('event_update', 'Event Update'), ('event_cancelled', 'Event Cancelled'), ('event_live', 'Event Goes Live'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('booking_success', 'Booking Success'), ('request_approved', 'Request Approved'), ('new_join_request', 'New Join Request'), ('ticket_confirmed', 'Ticket Confirmed'), ('event_started', 'Event Started'), ('payout_reminder', 'Payout Reminder'), ('reminder', 'Reminder'), ('system', 'System'), ('promotional', 'Promotional')], help_text='Type of notification', max_length=50),
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public UUID', unique=True)),
                ('name', models.CharField(help_text="Human-readable campaign name (e.g., 'Profile Incomplete Reminder - Bangalore Music')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description explaining why this campaign was created')),
                ('template_key', models.CharField(db_index=True, help_text="Template key from NotificationTemplate enum (e.g., 'profile_completion_reminder')", max_length=100)),
                ('template_variables', models.JSONField(blank=True, default=dict, help_text="Variable values for template rendering (e.g., {'event_name': 'Summer Music Fest'})")),
                ('audience_rules', models.JSONField(help_text="Audience selection rules in JSON format (e.g., {'all': [{'field': 'profile_completed', 'op': '=', 'value': false}]})")),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('previewed', 'Previewed'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='draft', help_text='Current campaign status', max_length=20)),
                ('preview_count', models.PositiveIntegerField(blank=True, help_text='Number of users matching audience rules (computed during preview)', null=True)),
                ('preview_computed_at', models.DateTimeField(blank=True, help_text='When preview was last computed', null=True)),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, help_text='When campaign was actually sent (null if not sent yet)', null=True)),
                ('total_sent', models.PositiveIntegerField(default=0, help_text='Total notifications successfully sent')),
                ('total_failed', models.PositiveIntegerField(default=0, help_text='Total notifications that failed to send')),
                ('execution_metadata', models.JSONField(blank=True, default=dict, help_text='Additional execution metadata (errors, warnings, batch info)')),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When campaign was cancelled (if applicable)', null=True)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason for cancellation (if applicable)')),
                ('cancelled_by', models.ForeignKey(blank=True, help_text='Admin user who cancelled this campaign', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_cancelled', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='Admin user who created this campaign', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_created', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(blank=True, help_text='Admin user who sent this campaign', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Campaign',
                'verbose_name_plural': 'Notification Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='Campaign that triggered this notification (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.campaign'),
        ),
        migrations.CreateModel(
            name='CampaignExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('sent_successfully', models.BooleanField(db_index=True, default=False, help_text='Whether notification was successfully delivered via OneSignal')),
                ('error_message', models.TextField(blank=True, help_text='Error message if delivery failed')),
                ('onesignal_response', models.JSONField(blank=True, default=dict, help_text='Raw OneSignal API response (for debugging)')),
                ('delivered_at', models.DateTimeField(blank=True, db_index=True, help_text='When notification was actually delivered', null=True)),
                ('campaign', models.ForeignKey(help_text='Parent campaign', on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='notifications.campaign')),
                ('notification', models.ForeignKey(help_text='Notification record created for this execution', on_delete=django.db.models.deletion.CASCADE, related_name='campaign_executions', to='notifications.notification')),
                ('user_profile', models.ForeignKey(help_text='User profile who received this notification', on_delete=django.db.models.deletion.CASCADE, related_name='campaign_notifications', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Campaign Execution',
                'verbose_name_plural': 'Campaign Executions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('onesignal_player_id', models.CharField(db_index=True, help_text='OneSignal player ID for this device', max_length=255, unique=True)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], help_text='Device platform', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this device is active (false if player ID invalid)')),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='Last time this device was seen/used', null=True)),
                ('user_profile', models.ForeignKey(help_text='User profile that owns this device', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='users.userprofile')),
            ],
            options={
                'ordering': ['-last_seen_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status'], name='notificatio_status_d747d5_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['template_key'], name='notificatio_templat_5d1168_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['created_at'], name='notificatio_created_093e8d_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['sent_at'], name='notificatio_sent_at_fd983e_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['created_by'], name='notificatio_created_3fa417_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignexecution',
            index=models.Index(fields=['campaign', 'sent_successfully'], name='notificatio_campaig_f0d236_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignexecution',
            index=models.Index(fields=['user_profile', 'sent_successfully'], name='notificatio_user_pr_f72b20_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignexecution',
            index=models.Index(fields=['delivered_at'], name='notificatio_deliver_3ab056_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['user_profile', 'is_active'], name='notificatio_user_pr_b69655_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['onesignal_player_id'], name='notificatio_onesign_3b5d56_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['is_active', 'last_seen_at'], name='notificatio_is_acti_5aaca7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userdevice',
            unique_together={('user_profile', 'onesignal_player_id')},
        ),
    ]
