# Generated by Django 5.2.1 on 2026-01-10 08:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_type_campaign_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public UUID', unique=True)),
                ('name', models.CharField(help_text="Template name (e.g., 'Profile Completion Reminder')", max_length=255, unique=True)),
                ('key', models.SlugField(help_text="Unique template key (e.g., 'profile_completion_reminder')", max_length=100, unique=True)),
                ('title', models.CharField(help_text="Notification title with {{variable}} placeholders (e.g., 'Complete Your Profile!')", max_length=200)),
                ('body', models.TextField(help_text="Notification message with {{variable}} placeholders (e.g., 'Hi {{name}}, complete your profile to join events!')")),
                ('target_screen', models.CharField(default='home', help_text="Mobile app screen to navigate to (e.g., 'profile', 'event_detail')", max_length=100)),
                ('notification_type', models.CharField(choices=[('event_request', 'Event Request'), ('event_invite', 'Event Invite'), ('event_update', 'Event Update'), ('event_cancelled', 'Event Cancelled'), ('event_live', 'Event Goes Live'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('booking_success', 'Booking Success'), ('request_approved', 'Request Approved'), ('new_join_request', 'New Join Request'), ('ticket_confirmed', 'Ticket Confirmed'), ('event_started', 'Event Started'), ('payout_reminder', 'Payout Reminder'), ('reminder', 'Reminder'), ('system', 'System'), ('promotional', 'Promotional')], default='system', help_text='Type of notification', max_length=50)),
                ('variable_hints', models.JSONField(blank=True, default=dict, help_text="Help text for each variable (e.g., {'event_name': 'Name of the event', 'user_name': 'Name of the user'})")),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is available for use')),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='campaign',
            name='notificatio_templat_5d1168_idx',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='template_key',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='audience_rules',
            field=models.JSONField(default=dict, help_text='Audience selection rules (auto-generated from UI fields)'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='template_variables',
            field=models.JSONField(blank=True, default=dict, help_text="Variable values for template rendering (e.g., {'event_name': 'Summer Music Fest', 'name': 'John'})"),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='created_by',
            field=models.ForeignKey(help_text='Admin user who created this template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Notification template to use (create new templates in Notification Templates)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='notifications.notificationtemplate'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['template'], name='notificatio_templat_b36c1d_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['key'], name='notificatio_key_86b139_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['is_active'], name='notificatio_is_acti_b2a982_idx'),
        ),
    ]
