# Generated by Django 5.2.1 on 2026-01-10 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notificationtemplate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='variable_hints',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='template_variables',
            field=models.JSONField(blank=True, default=dict, help_text='Variable values (auto-populated from UI fields, not directly edited)'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='body',
            field=models.TextField(help_text="Notification message with {{variable}} placeholders (e.g., 'Hi {{name}}, complete your profile to join events!' or 'New event: {{event_name}} by {{host_name}}')"),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this template is available for use in campaigns'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('event_request', 'Event Request'), ('event_invite', 'Event Invite'), ('event_update', 'Event Update'), ('event_cancelled', 'Event Cancelled'), ('event_live', 'Event Goes Live'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('booking_success', 'Booking Success'), ('request_approved', 'Request Approved'), ('new_join_request', 'New Join Request'), ('ticket_confirmed', 'Ticket Confirmed'), ('event_started', 'Event Started'), ('payout_reminder', 'Payout Reminder'), ('reminder', 'Reminder'), ('system', 'System'), ('promotional', 'Promotional')], default='system', help_text='Type of notification (affects how it appears to users)', max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='target_screen',
            field=models.CharField(default='home', help_text="Mobile app screen to navigate to when user taps notification (e.g., 'profile', 'event_detail', 'home')", max_length=100),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='title',
            field=models.CharField(help_text="Notification title with {{variable}} placeholders (e.g., 'Complete Your Profile!' or 'Hi {{name}}, check out {{event_name}}!')", max_length=200),
        ),
        migrations.CreateModel(
            name='TemplateVariableHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('variable_name', models.CharField(help_text="Variable name (without braces, e.g., 'event_name')", max_length=100)),
                ('help_text', models.TextField(help_text="Help text explaining what this variable is for (e.g., 'Name of the event')")),
                ('template', models.ForeignKey(help_text='Template this hint belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='variable_hints_list', to='notifications.notificationtemplate')),
            ],
            options={
                'verbose_name': 'Template Variable Hint',
                'verbose_name_plural': 'Template Variable Hints',
                'ordering': ['variable_name'],
                'unique_together': {('template', 'variable_name')},
            },
        ),
    ]
