# Generated by Django 5.2.1 on 2026-01-10 09:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_remove_notificationtemplate_variable_hints_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='template_version',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Immutable template version snapshot at campaign creation time. Used for audit trail and analytics.', null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='version',
            field=models.PositiveIntegerField(db_index=True, default=1, help_text='Template version number. Incremented on content changes. Campaigns store immutable version snapshot.'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationtemplate',
            unique_together={('key', 'version')},
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['key', 'version'], name='notificatio_key_881120_idx'),
        ),
    ]
